documented wordpress multisite settings
docksal/docksal pull request #1432
Opened 2020-11-13 20:04 UTC by sean-e-dietrich

Closes #1428

2020-11-13 21:02 UTC, shelane requested changes
Just one comma needed.

2020-11-13 21:02 UTC, shelane commented on docs/content/tools/wordpress.md
> +When converting a single site to a multi-site there can be some issues that occur with
...to a multi-site, there...

2020-11-20 19:04 UTC, lmakarov commented on docs/content/tools/wordpress.md
> +When converting a single site to a multi-site there can be some issues that occur with
```suggestion
When converting a single site to a multi-site, there can be some issues that occur with 
```

2020-11-20 19:04 UTC, lmakarov approved these changes

2020-11-20 19:05 UTC, merged