Added option for addons and other files to source the fin file
docksal/docksal pull request #1465
Opened 2021-02-13 23:09 UTC by sean-e-dietrich

Added option so that `fin` could be sourced for addons and commands and take advantage of the functions already provided in the main file.

Example of the usage:

```bash
# Find the fin command
fin=`which fin`

# Source the file to use functions
[[ -f ${fin} ]] && source $fin
```

2021-02-15 17:00 UTC, lmakarov requested changes
Look's harmless to me. Why not.

@sean-e-dietrich please also add a note in the docs about this use case.

2021-02-23 21:36 UTC, shelane commented on docs/content/fin/custom-commands.md
> +To reuse some of the functionality within the `fin` command like `parse_params`, `is_linux`, or any of the functions it's possible to source the `fin` file.
It is possible to source the `fin` file in order to reuse some of the functionality within the `fin` command like `parse_params`, `is_linux`, or any of the functions.

2021-03-09 21:24 UTC, shelane approved these changes

2021-03-11 12:50 UTC, achekulaev approved these changes

2021-03-20 18:04 UTC, lmakarov approved these changes

2021-03-20 18:04 UTC, merged