Issue #1476 Updates provider_pull_acquia_db()
docksal/docksal pull request #1480
Opened 2021-03-23 14:20 UTC by acouch

#1476

This updates `fin pull db` for Acquia.

This removes the code that checks for the latest backup since acquiacli does this with it's backup command: https://github.com/typhonius/acquia_cli/blob/master/src/Commands/DbBackupCommand.php#L183

This requires adding a new variable `ACQUIA_REALM` for ACP users. Would of course update the docs if this is pulled in.

2021-03-23 15:05 UTC, shelane requested changes
We are no longer using the Typhonius Acquia CLI, but the Acquia CLI from Acquia. Please refer to those commands.

2021-03-23 18:49 UTC, acouch commented
Can you say more? Your [docs](https://docs.docksal.io/tools/acquia-cli/) and [default cli](https://github.com/docksal/service-cli/blob/develop/README.md#hosting-provider-tools) still include the Typhonius CLI.

2021-03-23 19:06 UTC, shelane commented
We'll update the docs. Thanks.

2021-07-02 05:47 UTC, shelane commented
Completed in #1492

2021-07-02 05:48 UTC, shelane commented
Sorry, that was a documentation only PR.

2021-07-30 15:37 UTC, shelane commented on bin/fin
> +	local realm=${ACQUIA_REALM:-prod}
What is this variable `ACQUIA_REALM` and where is it set? Should that be using the `HOSTING_SITE` variable? [See docs](https://docs.docksal.io/fin/fin-pull/#initializing-project)

2023-01-23 16:22 UTC, acouch commented
Closing this as I don't have the opportunity to continue working on it. Thank you.

2023-01-23 16:22 UTC, closed without merging