Add `--progress` option to `provider_pull_db`
docksal/docksal pull request #1559
Opened 2021-08-31 18:08 UTC by rmott-littler

Adding a progress bar for `fin pull db`. `pv` already available in cli.

2021-11-28 06:38 UTC, sean-e-dietrich requested changes
Overall found this pretty useful and helpful! Just looking for those 3 changes to the help text.

2021-11-28 06:38 UTC, sean-e-dietrich commented on bin/fin
> +	printh "--progress" "Show import progress."
Remove `.` from the end

2021-11-28 06:38 UTC, sean-e-dietrich commented on docs/content/fin/fin-help.md
> +	  --progress               	Show import progress.
Please remove period from end of help text

2021-11-28 06:38 UTC, sean-e-dietrich commented on docs/content/fin/fin-pull.md
> +  --progress                    Show import progress.
Please remove period from end of help text

2022-02-21 22:38 UTC, lmakarov commented
ping @sean-e-dietrich

2022-04-01 20:10 UTC, lmakarov commented
`pull` command was moved to the docksal/addons repo. See https://github.com/docksal/docksal/pull/1641 and https://github.com/docksal/addons/pull/78

2022-04-01 20:10 UTC, closed without merging