Update fin
docksal/docksal pull request #1563
Opened 2021-09-06 05:37 UTC by sean-e-dietrich

2021-11-15 22:45 UTC, shelane requested changes
Just getting a head start on the review ;-)

2021-11-15 22:45 UTC, shelane commented on docs/content/use-cases/gitpod.md
> +[Gitpod](https://www.gitpod.io/) is an only development environment.
Consider "Gitpod is a browser-based development environment."
or
"Gitpod is a browser only development environment."

But, it probably needs a bit more explanation.

2021-11-15 22:45 UTC, shelane commented on docs/content/use-cases/gitpod.md
> +To get started create a `.gitpod.yml` file within your project.
Add comma:
To get started, create a ...

2021-11-15 22:45 UTC, shelane commented on docs/content/use-cases/gitpod.md
> +Once created you are ready to start your project within the [Gitpod Workspace](https://www.gitpod.io/docs/getting-started).
Add comma:
Once created, you are ready...

2021-11-15 22:45 UTC, shelane commented on docs/content/use-cases/gitpod.md
> +For more information on creating the Gitpod Configuration file. Consult the [Gitpod Getting Started](https://www.gitpod.io/docs/getting-started)
Change period to comma:
... on creating the Gitpod configuration file, consult the...

2021-11-29 19:50 UTC, shelane approved these changes
Docs look good.

2022-04-01 17:20 UTC, lmakarov approved these changes

2022-04-01 20:07 UTC, merged