Solr 8 instructions.
docksal/docksal pull request #1578
Opened 2021-10-06 22:00 UTC by danshumaker

Added instructions for Solr 8.

Regarding: https://github.com/docksal/docksal/issues/1152

2021-10-13 03:37 UTC, dshumakerUT commented
> Don't delete the submodule the docs theme learn. That is needed for our documentation site.

Restored.

2022-03-05 16:23 UTC, danshumaker commented
@shelane @lmakarov   I use gitlab 99% of the time.  Github is slightly different.  Please let me know if the new changes are to your liking. Commit 82619e8e.

2022-12-07 00:53 UTC, shelane requested changes

2022-12-07 00:53 UTC, shelane commented on docs/content/service/other/apache-solr.md
> +Once you have configured your solr instance in the Drupal Admin, and then
Either remove the comma or the "and" here.

2022-12-09 16:55 UTC, merged