updates documentation to use fin config set where appropriate
docksal/docksal pull request #1666
Opened 2022-04-19 17:18 UTC by shelane

closes #1665

2022-04-19 18:05 UTC, lmakarov requested changes

2022-04-19 18:05 UTC, lmakarov commented on docs/content/tools/acquia-cli.md
> -Note: It is also possible to add/override these values via `.docksal/docksal-local.env` at the project level.
I'd either add an example with `fin config set --env=local ...` or just mention that `--global` can be replaced with `--env=local` to achieve this.

2022-04-19 18:05 UTC, lmakarov commented on docs/content/tools/platformsh.md
> +{{% notice note %}}
This notice should be the same among all hosting provider integrations.

2022-04-20 03:47 UTC, shelane commented
Changes made.

2022-04-27 19:41 UTC, lmakarov approved these changes

2022-04-27 19:41 UTC, merged